#include "CheckerKennedy.h"




void CheckerKennedy::CheckerKennedy()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1-285932e:139f7e73103:-8000:0000000000001267 begin
{
}
// section 127-0-0-1-285932e:139f7e73103:-8000:0000000000001267 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void CheckerKennedy::checkProposedMove(void  Polymer)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1-285932e:139f7e73103:-8000:000000000000126D begin
{
}
// section 127-0-0-1-285932e:139f7e73103:-8000:000000000000126D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
