#include "MCMCSimulator.h"




void MCMCSimulator::MCMCSimulator()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1-285932e:139f7e73103:-8000:0000000000001221 begin
{
}
// section 127-0-0-1-285932e:139f7e73103:-8000:0000000000001221 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void MCMCSimulator::MCMCSimulator(void  InputParameters)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1-285932e:139f7e73103:-8000:000000000000122C begin
{
}
// section 127-0-0-1-285932e:139f7e73103:-8000:000000000000122C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void MCMCSimulator::run()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1-285932e:139f7e73103:-8000:0000000000001235 begin
{
}
// section 127-0-0-1-285932e:139f7e73103:-8000:0000000000001235 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
