#include "ModifiedPivot.h"




void ModifiedPivot::ModifiedPivot()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1-285932e:139f7e73103:-8000:0000000000001251 begin
{
}
// section 127-0-0-1-285932e:139f7e73103:-8000:0000000000001251 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void ModifiedPivot::move(void  angle, void  monomer)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1-285932e:139f7e73103:-8000:0000000000001253 begin
{
}
// section 127-0-0-1-285932e:139f7e73103:-8000:0000000000001253 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
