#include "Monomer.h"




Vector3D Monomer::getPosition()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1-285932e:139f7e73103:-8000:00000000000011FC begin
{
}
// section 127-0-0-1-285932e:139f7e73103:-8000:00000000000011FC end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Vector3D Monomer::setPosition()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1-285932e:139f7e73103:-8000:00000000000011FE begin
{
}
// section 127-0-0-1-285932e:139f7e73103:-8000:00000000000011FE end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Integer Monomer::getIndex()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1-285932e:139f7e73103:-8000:0000000000001200 begin
{
}
// section 127-0-0-1-285932e:139f7e73103:-8000:0000000000001200 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Monomer::Monomer()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1-285932e:139f7e73103:-8000:0000000000001202 begin
{
}
// section 127-0-0-1-285932e:139f7e73103:-8000:0000000000001202 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Monomer::Monomer(void  index, void  position)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1-285932e:139f7e73103:-8000:0000000000001204 begin
{
}
// section 127-0-0-1-285932e:139f7e73103:-8000:0000000000001204 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
