#include "MonomerMover.h"




void MonomerMover::MonomerMover()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1-285932e:139f7e73103:-8000:0000000000001241 begin
{
}
// section 127-0-0-1-285932e:139f7e73103:-8000:0000000000001241 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void MonomerMover::move(void  angle)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1-285932e:139f7e73103:-8000:0000000000001243 begin
{
}
// section 127-0-0-1-285932e:139f7e73103:-8000:0000000000001243 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
