#include "MoveChecker.h"




void MoveChecker::MoveChecker(void  slabSpacing, void  bondLength)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1-285932e:139f7e73103:-8000:0000000000001258 begin
{
}
// section 127-0-0-1-285932e:139f7e73103:-8000:0000000000001258 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void MoveChecker::checkProposedMove(void  Polymer)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1-285932e:139f7e73103:-8000:000000000000125A begin
{
}
// section 127-0-0-1-285932e:139f7e73103:-8000:000000000000125A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
