#include "Pivot.h"




void Pivot::Pivot()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1-285932e:139f7e73103:-8000:0000000000001248 begin
{
}
// section 127-0-0-1-285932e:139f7e73103:-8000:0000000000001248 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Pivot::move(void  angle, void  monomer)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1-285932e:139f7e73103:-8000:000000000000124D begin
{
}
// section 127-0-0-1-285932e:139f7e73103:-8000:000000000000124D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
