#include "Polymer.h"




void Polymer::Polymer()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1-285932e:139f7e73103:-8000:0000000000001212 begin
{
}
// section 127-0-0-1-285932e:139f7e73103:-8000:0000000000001212 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Polymer::Polymer(void  Nmonomers)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1-285932e:139f7e73103:-8000:0000000000001214 begin
{
}
// section 127-0-0-1-285932e:139f7e73103:-8000:0000000000001214 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
